### ISSUE TITLE
Graph lines are too close together in large repos

### ISSUE THREAD

**Issue by adalisk-emikhaylov** [phil294/git-log--graph#45]
Here's the same graph in your extension and in Git Graph:

![image](https://github.com/phil294/git-log--graph/assets/69473580/5dbfd138-bd13-4cf8-8afd-c8a082e1f6ca)

![image](https://github.com/phil294/git-log--graph/assets/69473580/11176d9c-2de6-4920-9d0d-7e8efdfb0fff)

**Comment by phil294** [comment]
this is discussed in #22: In your case, the branches are this dense because at some point further down you'll have hundreds of them next to each other, and we reserve the place for those from the start because 15,000 commits are loaded and "rendered" by default. You can mitigate this a bit by setting `"git-log--graph.branch-width"` to a custom value, usually between 2 and 10. But then it can be shown *on top of* the commit messages at some point, so it's not great.

The proper solution to this is to make all columns resizable, so that nothing needs to be cramped, wide branch areas will be hidden and you can just adjust everything at will. But I can't promise that I'll get to work on that very soon.

**Comment by phil294** [comment]
you can now resize the branch area so this should be fixed
