### ISSUE TITLE
Toggle Graph View

### ISSUE THREAD

**Issue by yougotwill** [phil294/git-log--graph#49]
It would be great to have a toggle the graph i.e. open or close. Right now we can only open it.

Also great work on the latest release things feel very smooth!

**Comment by AddictArts** [comment]
+1 Is it possible to add activation button on the Activity Bar, which is default the left side of VS Code window?

**Comment by phil294** [comment]
@AddictArts just so I understand right, you want to be able to click an icon on the Activity Bar for then for the main view to show up somewhere *else* (such as bottom view or main web view)? This sounds strange to me especially since clicking an icon doesn't really "do" anything, instead it only toggles the display of submenus / views. You could put git-log--graph *inside* an activity bar section, but that's probably not what you meant. https://code.visualstudio.com/api/ux-guidelines/activity-bar says "❌ Don't Use an Activity Bar item to open a Webview Panel" even though I don't know how that should possible. Anyway, it doesn't seem like it is possible right now: https://stackoverflow.com/a/70685722/3779853 https://code.visualstudio.com/updates/v1_23#_contributions-to-the-activity-bar https://code.visualstudio.com/api/references/contribution-points#contributes.viewsContainers

But perhaps you'll find another extension similar to https://marketplace.visualstudio.com/items?itemName=Gruntfuggly.activitusbar that adds another toolbar somewhere you like so you can put our command there!

**Comment by phil294** [comment]
another one (albeit sometimes hidden) is here 
![imagen](https://github.com/phil294/git-log--graph/assets/14108705/da0bc5db-2f06-4590-99c8-af45f7032fa2)

**Comment by yougotwill** [comment]
> +1 Is it possible to add activation button on the Activity Bar, which is default the left side of VS Code window?

Not quite the same thing.

What I would like is something like another keyboard shortcut that closes the graph view (and or the panel it's in) the opposite of git log `--graph: Open graph view (git-log--graph.start)`. Ideally it should just be 1 command that toggles aka. Opens or Closes the graph view.
