### ISSUE TITLE
Command failed:fatal: unrecognized %(upstream:remotename) argument: remotename

### ISSUE THREAD

**Issue by ImanMahmoudinasab** [phil294/git-log--graph#52]
I can't use the extension due to the following issue:

<img width="963" alt="image" src="https://github.com/phil294/git-log--graph/assets/5295554/bc097ba6-e80e-45b1-bc64-cb8334d7d8f0">

**Comment by phil294** [comment]
Hi! Can you please share your `git --version`?

**Comment by phil294** [comment]
Looks like your Git is older than v2.16 which is when this was added https://github.com/git/git/commit/cc72385fe350d4d7bc64f84e8817dbdfe27b04fe. Even debian's oldest lts release buster ships with the more recent version v2.20 https://packages.debian.org/buster/git

so my bet is on you using windows and you having downloaded Git manually 5 years ago and not having updated it ever since :-)

would updating it be an option for you? I'm afraid I can't really offer support for outdated versions currently.

**Comment by ImanMahmoudinasab** [comment]
Hi Philip! 
Thank you for the support. 
You are right the issue was with my git binary version. On my mac it was stuck with version 2.15, even with `brew install git` and `brew upgrade git`. I was able to fix it with running `sudo rm '/usr/local/bin/git'`  command. Now my terminal is using the git that is installed with brew.
