### ISSUE TITLE
Is there a plan to add the functionality of commit modified files?

### ISSUE THREAD

**Issue by victorwwd** [phil294/git-log--graph#55]
Is there a plan to add the menu of commit modified or stashed files?
And diff between two commits is also what i need.

**Comment by phil294** [comment]
> commit modified files

I'm not entirely sold on this - can't you already see the current work tree changes in VSCode's native SCM side bar view already? Git Graph does it also, but I never used it, so need some explanation on this.

> stashed files

A Git repository can have an arbitrary amount of stashes, so there isn't just *one* stash. Any stash you create should be shown in the interface though. If this is too hidden / not obvious enough (it seems to be, since you asked for it), I'd welcome improvements suggestions!

> diff between two commits

This is already possible by clicking on a commit and then <kbd>Ctrl</kbd>-click on a second commit. A small comparison dialog will open up. It's a bit of a hidden feature though... still looking for ways to improve that. For now, I will add a small note at the bottom of the commit details view, right below "Parent commits".

**Comment by victorwwd** [comment]
I thought it would be convenient to do something like commit or rebase in the same interface, but without this feature, it's ok.

By the way,  can branch name be placed together with commit, just like a 'Git Graph'? and the commit column can be dragged to prevent the commit content from being squeezed?

And there seems to be a little too much white space at the top of the extension?

**Comment by phil294** [comment]
> By the way, can branch name be placed together with commit, just like a 'Git Graph'?

let's move this here #44 

> and the commit column can be dragged to prevent the commit content from being squeezed?

this is now possible by dragging the colored circles next to the commit messages #22

> And there seems to be a little too much white space at the top of the extension?

yeah well it's not quote unused, is it 🤷

initially it shows the output of `git status` which I find quite useful (albeit not very pretty)

![image](https://github.com/phil294/git-log--graph/assets/14108705/43ed136a-fa40-4563-a974-51b3f9ca2244)

and once you scroll down it gives you an overview of what the currently visible branches are:

![image](https://github.com/phil294/git-log--graph/assets/14108705/f5739f15-aea4-4f59-9453-694b148b740e)

definitely room for improvement, but let's continue that in #28 

so I think this very issue can be closed :)
