### ISSUE TITLE
`checkout` error

### ISSUE THREAD

**Issue by BachiMjavanadze** [phil294/git-log--graph#63]
This error occurs when doing simple `checkout` using your extension UI (graph):

![image](https://github.com/phil294/git-log--graph/assets/38082501/50af7c8e-675e-4fde-8888-4dcddd502ec9)

I'm on `Windows 11 Home`.

**Comment by phil294** [comment]
Thanks for the report. This was caused by the presence of `'`s in almost all commands, which seems to not be supported by Windows (#4). This means that this extension probably didn't work at all on Windows (non-WSL) for at least 6 months?? I thought we had some Windows users but apparently not.

Not sure in how bad of a state Windows support is in general right now, I guess I'll borrow myself a laptop soon and see if other things break too.
