### ISSUE TITLE
improve error message when git input was modified

### ISSUE THREAD

**Issue by hansu** [phil294/git-log--graph#66]
After using my VM after some time again, I get this error when trying to run this extension:

![grafik](https://github.com/phil294/git-log--graph/assets/67957916/7354b804-d3d0-496c-b6fb-d93b6e79a981)

When I run Code it with a clean `--user-data-dir` then it works. But I don't want to delete my user data dir. Any hints what this could cause?

**Comment by phil294** [comment]
"unknown visuals at row 0" means the output returned from git's `log` command has an unknown format. I guess this can happen if you have changed the log command (very top in the main view)? Perhaps you have adjusted something there which used to work, but then I broke it unintentionally in a subsequent update. Could you share what this field holds for you currently, *if* it is shown as modified? *Before* clicking on "Reset", as then the error will not be reproducible anymore.

Otherwise, you could try setting the config flag `verbose-logging` to `true`. Afterwards, you can open the "Output" view and select `git log --graph`. This view should also contain the error, and more information around it - such as said git output. If you paste the relevant information here, I'm sure we'll find something.

Anyway, the error handling should be improved here: If any of the git inputs (including the main `log` one) return an error *and* the user has altered the input command, there should be a message suggesting them to click "reset" to potentially fix the error. These kinds of errors are rather unique to this extension, I don't think there is an easy way to prevent them, really. I guess that's the downside of exposing such powerful functionality to the extension user :|

**Comment by hansu** [comment]
The line was
`log --graph --oneline -n 50 --skip=0 --all {STASH_REFS} --invert-grep --grep="^untracked files on " --grep="^index on "  --author-date-order`

and it seems the `--pretty={EXT_FORMAT} ` was missing.

Thanks for that hint, now it works again :smile:

**Comment by phil294** [comment]
ok great

allow me to reopen so keep a reminder to myself to take care of the error message problem from my previous message

**Comment by hansu** [comment]
> allow me to reopen so to keep a reminder to myself to take care of the error message problem from my previous message

Sure :)
